### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Japanese#10]
We should've kept the **Home, Faculty and Next Stops** navigation tabs like the Arabic page. In Japanese, the same content is repeated on the home page and on the undergraduate page. 

So for Japanese we now have **Home, Undergraduate, Faculty with no Next Stops page** (which I thought all programs were supposed to have as it houses the admissions and deadlines information) and the same content repeated on Home and Undergraduate.

**Comment by tu-chill** [comment]
Yes. We'll need to add the Next Stops page. It's the whole temple cheesy train metaphor. I didn' t make it up and how I feel about it doesn't matter. Temple is using it and so shall we. @camille do what you know is right.

**Comment by CVE82** [comment]
Fixed the navigation tabs, we are all good again!
