### ISSUE TITLE
Landing page image/hero

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Japanese#4]
Hero image just needs to be sized and placed, please and thank you.

**Comment by pixelyunicorn** [comment]
The hero image can be found at http://develop.cla.temple.edu/japanese/media/iStock_Japanese%20Mt.%20Fuji.jpg

**Comment by ZMcGroarty** [comment]
![hero_japanese-min](https://cloud.githubusercontent.com/assets/15017242/23415380/08816f64-fdad-11e6-9e0d-04a06b862bae.png)

**Comment by CVE82** [comment]
LOVE, AGAIN!
