### ISSUE TITLE
Spacing issue on Japanese faculty page

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Japanese#9]
Temple T placeholders running together on this page http://develop.cla.temple.edu/japanese/faculty/

**Comment by tu-chill** [comment]
Screenshot and browser info

**Comment by CVE82** [comment]
![image](https://cloud.githubusercontent.com/assets/15130721/24007079/f8f78e7c-0a43-11e7-8eb9-c9fb1fe5fa38.png)

**Comment by pixelyunicorn** [comment]
I'll set a min-height for these elements

**Comment by CVE82** [comment]
Thanks!
